import os

KONZUM_KLIK_USERNAME = os.environ.get('KONZUM_KLIK_USERNAME')
KONZUM_KLIK_PASSWORD = os.environ.get('KONZUM_KLIK_PASSWORD')

SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY')
NOTIFY_TO_ADDRESS = os.environ.get('NOTIFY_TO_ADDRESS')
NOTIFY_FROM_ADDRESS = os.environ.get('NOTIFY_FROM_ADDRESS')
